# Generated by Django 4.1.2 on 2023-01-23 15:13

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(db_index=True, max_length=200, verbose_name='наименование категории')),
                ('category_slug', autoslug.fields.AutoSlugField(blank=True, default=None, editable=False, populate_from='category_name', unique=True, verbose_name='SLUG')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('category_name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='наименование товара')),
                ('slug', models.SlugField(max_length=200, verbose_name='SLUG')),
                ('image', models.ImageField(blank=True, upload_to='products', verbose_name='фото')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('price', models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='цена')),
                ('stock', models.PositiveIntegerField(blank=True, null=True, verbose_name='запас')),
                ('available', models.BooleanField(blank=True, default=True, null=True, verbose_name='доступный')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name=' дата создания')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='дата обновления')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('name',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
